# Generated by Django 5.0.6 on 2024-06-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='approvereqdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donorname', models.CharField(blank=True, max_length=100, null=True)),
                ('donorage', models.IntegerField(blank=True, null=True)),
                ('disease', models.CharField(blank=True, max_length=100, null=True)),
                ('bloodgroup', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donordb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='pics')),
                ('Bloodgroup', models.CharField(blank=True, max_length=100, null=True)),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('Contact', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
