# Generated by Django 5.0.6 on 2024-07-01 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donorandpatient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makerequestdb',
            name='unit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
